### ISSUE TITLE
Fit to container width

### ISSUE THREAD

**Issue by blaenk** [grubersjoe/react-activity-calendar#1]
Very beautiful component!

I'm trying to figure out how to get it to fit the width of the container I embed it in. It seems like the width is determined concretely in pixels based on the grid size etc.

Experimenting with dev tools it seems like I can delete the `<article>` `width: 100px` and the child `<svg>` `width` _and_ `height` attributes, and that seems to fit it to the width just fine in a responsive manner, as I resize the page.

Not sure if I'm just not passing the right properties or if this is indeed something that would have to be added to the component.

Thank you for creating this!

**Comment by grubersjoe** [comment]
Hey. Sorry for the late response. Setting the container width explicitly is not useful, I agree. I have removed the inline style, so it should automatically scale now.
