### ISSUE TITLE
choose to render weekends or not

### ISSUE THREAD

**Issue by BensimonSamy** [grubersjoe/react-activity-calendar#12]
Currently it's not possible to choose witch days to render. I would like to hide Saturday and Sunday for example

**Comment by grubersjoe** [comment]
Hey. I like the idea :+1:. Should be pretty easy to add.

Or did you change your mind (because you closed the issue)?

**Comment by BensimonSamy** [comment]
I finally found a tricks in css. But I saw you release to do that more niecely. Thanks a lot !  🥳
