### ISSUE TITLE
How to make a toggle for switch theme of the component?

### ISSUE THREAD

**Issue by maodaisuki** [grubersjoe/react-activity-calendar#124]
Hi, could you tell me how to switch the theme of the calendar, I am trying the code like below: 
```tsx
const explicitTheme: ThemeInput = {
    light: ['#d7d9db', '#9be9a8', '#40c463', '#30a14e', '#216e39'],
    dark: ['#323942', '#39d353', '#26a641', '#006d32', '#0e4429'],
};
...
<ActivityCalendar
...
    theme={explicitTheme}
    colorScheme={localstroage.getItem('theme') || 'light'}
...
/>
``` 
and I have a button to change the value of `theme`, my page theme is changed, but it didn't work on `ActivityCalendar`.

**Comment by grubersjoe** [comment]
Hey. React does not know about changes in the local storage. You can listen to changes in a `useEffect()` or, and I think that's probably better, you restructure you code to something like this:

https://codesandbox.io/p/devbox/6jm9f7

```tsx
import { useState } from "react";

const themeKey = 'theme';

function App() {
  const [theme, setTheme] = useState(localStorage.getItem(themeKey) ?? 'light');

  const toggleTheme = () => {
    const updatedTheme = theme === 'light' ? 'dark' : 'light';
    localStorage.setItem(themeKey, updatedTheme)
    setTheme(updatedTheme)
  }

  return (
    <>
      <h3>chosen theme: {theme}</h3>
      <button type="button" onClick={() => toggleTheme()}>toggle theme</button>
    </>
  );
}

export default App;
```

**Comment by maodaisuki** [comment]
Hi, thank you for your reply. Maybe my question is not so clear. I wanted to make a toggle in another component file and the layer like: 
```
└─ActivityCalendar.tsx
└─AnotherComponentWithToggle.tsx
```
so if in this case, use `useState` is not so convenient for me, in fact it probably can't work, and I had solved in this question with move my toggle into `ActivityCalendar.tsx` in the end :D, so maybe this issue is a little bad, I am sry for that.

**Comment by grubersjoe** [comment]
If you need the theme state in several components maybe context is a good option:
https://react.dev/learn/passing-data-deeply-with-context

Here the color theme is even used as example throughout the page:
https://react.dev/reference/react/useContext
