### ISSUE TITLE
How to render specific tile color?

### ISSUE THREAD

**Issue by jalpp** [grubersjoe/react-activity-calendar#142]
I was curious how this can be done. using Render block seems most ideal but not sure, Is there another prop I can pass in?

**Comment by grubersjoe** [comment]
Do you mean how to define a color theme or do you want to change the color of a single block?
For the first case this page should answer your question: [Color themes](https://grubersjoe.github.io/react-activity-calendar/?path=/story/react-activity-calendar--color-themes).

**Comment by jalpp** [comment]
> Do you mean how to define a color theme or do you want to change the color of a single block? For the first case this page should answer your question: [Color themes](https://grubersjoe.github.io/react-activity-calendar/?path=/story/react-activity-calendar--color-themes). In the second case `renderBlock` is probably best, yes.

I meant to change the color of titles randomly. I was also wondering if I could replace the tile with, say, an icon, like marking a tile on the calendar with a checkbox icon.

**Comment by grubersjoe** [comment]
Yes, for these kind of things `renderBlock` is your best bet.
