### ISSUE TITLE
Cannot render calendar with only one week of data

### ISSUE THREAD

**Issue by nc-simv** [grubersjoe/react-activity-calendar#18]
If there is only one week of data there I get a 
```
TypeError: Cannot read properties of undefined (reading 'map')
```
on https://github.com/grubersjoe/react-activity-calendar/blob/main/src/component/ActivityCalendar.tsx#L187

The reason seems to be that the `groupByWeeks` logic pads to one week but we try to access index 1 in the week array which may not be present. It is not clear to me if this could be fixed by accessing index 0 instead of one, or if `groupByWeeks` should add an extra week if there is only data for one week.

**Comment by grubersjoe** [comment]
Closing this, feel free to reopen if there's still an issue.

**Comment by nc-simv** [comment]
It works. Thank you so much for the quick response. Great work on the calendar i have enjoyed using it.
