### ISSUE TITLE
End on current date

### ISSUE THREAD

**Issue by blaenk** [grubersjoe/react-activity-calendar#2]
Something possible on the github contribution heatmap as well as on https://github.com/kevinsqi/react-calendar-heatmap is the ability for the contribution heatmap to end on the current date, meaning the current date is the last item, and the rest of the left side of the heatmap conveys the entire past year.

Not sure if this is already possible by simply rotating the data array?

That might be nice to support!

**Comment by blaenk** [comment]
Otherwise/in addition it might be nice to be able to style the current date differently, maybe with an inward border or something, to easily find it.

**Comment by grubersjoe** [comment]
Hey. Sorry for the late reply. I think this is out of scope of this component. Simply transform your input data to match the desired time span please.
