### ISSUE TITLE
Code examples on storybook

### ISSUE THREAD

**Issue by Jordan-Loeser** [grubersjoe/react-activity-calendar#20]
Very helpful component! It would be great if you could provide code samples (or clearer instructions on how to view them) along with the storybooks. Usually I see a "show code" button on storybook but it doesn't seem to be available.

**Comment by grubersjoe** [comment]
Hey. It's been a while, but I came up with something now. The automatic code snippets generated by Storybook were pretty useless, so I've added handwritten ones on the docs page:

https://grubersjoe.github.io/react-activity-calendar/?path=/docs/react-activity-calendar--docs
