### ISSUE TITLE
Weekday label cut off when using mantine-ui

### ISSUE THREAD

**Issue by chiahsoon** [grubersjoe/react-activity-calendar#21]
Hey, thanks for the fantastic component!

I'm currently using [mantine-ui](https://github.com/mantinedev/mantine) for my project and when using react-activity-calendar, it seems that the weekday label is cut-off. It looks like this:

![Screenshot 2022-08-01 at 9 02 32 PM](https://user-images.githubusercontent.com/25706421/182153862-0178d1c4-6c94-47ee-abb2-d23c68d39453.png)

This problem only occurs with mantine-ui, not with vanilla react/next.js. When I tried debugging it, it seems like the only way I could make it appear by changing the `x` value of the label to something larger. For example, i changed `<text x="-8" y="49" text-anchor="end">Mon</text>` to `<text x="100" y="49" text-anchor="end">Mon</text>` and the component now looks like this:

![Screenshot 2022-08-01 at 9 04 16 PM](https://user-images.githubusercontent.com/25706421/182154149-617fc9a5-87df-457f-afce-86a36d7d16ed.png)

I know this is technically a problem of mantine, but since this seems like a general styling issue I just wanted to check if you have any clue how I can possibly fix this from my end?

Thank you so much!

**Comment by lws803** [comment]
It's breaking for me here as well :x I've found a quick and dirty way to fix this though, I would wrap the ActivityCalendar in a mantine Box and override certain styles by setting margin left to 0 and increasing the width of that svg.

```ts
<Box
  sx={() => ({
    ".react-activity-calendar__calendar": {
      width: "924px",
      marginLeft: 0,
    },
  })}
>
  <ActivityCalendar
...
```
