### ISSUE TITLE
@types/tinycolor2 should probably be in "dependencies" instead of "devDependencies".

### ISSUE THREAD

**Issue by krafftsimon** [grubersjoe/react-activity-calendar#22]
Right now if you are using TypeScript with this package and you only `npm install react-activity-calendar`, TypeScript will complain that it cannot find a declaration file for the `tinycolor2` module. This is because `@types/tinycolor2` is in `devDependencies` instead of `dependencies` and therefore doesn't get installed when you only `npm install react-activity-calendar`.

IMO, it would be cleaner to have `@types/tinycolor2` be in `dependencies` instead of `devDependencies`. It would avoid having to add an extra `@types` package to our `package.json` and it may be confusing to other devs missing context around this issue.

Related SO answer: https://stackoverflow.com/a/46011417

**Comment by grubersjoe** [comment]
Hey. Good point, I agree `@types/tinycolor2` should be moved to the `dependencies`. Thanks for pointing this out.

**Comment by krafftsimon** [comment]
> Released in `react-activity-calendar@1.6.1`.

Awesome, thanks for making the change.
