### ISSUE TITLE
Failed to compile in create-react-app & typescript

### ISSUE THREAD

**Issue by binh-vu** [grubersjoe/react-activity-calendar#24]
I want to use your package (version 1.6.2) but I encounter this error:

```
./node_modules/react-activity-calendar/build/index.js 293:80
Module parse failed: Unexpected token (293:80)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const weeks = groupByWeeks(data, weekStart);
|   const totalCount = data.reduce((sum, day) => sum + day.count, 0);
>   const year = getYear__default["default"](parseISO__default["default"](data[0]?.date));
|   const theme = getTheme(themeProp, color);
|   const labels = Object.assign({}, DEFAULT_LABELS, labelsProp);
```

It seems like I need to add an extra babel plugin to compile `?`. I look into your babel.config.json file and I think I may need to use: `@babel/plugin-proposal-nullish-coalescing-operator`. I google how to do it and it seems quite complex to add a babel plugin with create-react-app. If this is not the case, can you please advise me how to fix it? Otherwise, I think it would be nice if people can use this package without the extra plugin :)

**Comment by grubersjoe** [comment]
Hey. `@babel/plugin-proposal-nullish-coalescing-operator` is already used in this project, for `?.` you need `@babel/plugin-proposal-optional-chaining`. However, I've tested it with the current version of `create-react-app` and was able to compile just fine.

```shell
npx create-react-app my-app --template typescript
# added <ActivityCalendar data={data} /> in App.tsx
yarn build
```

What version of CRA are you using? Can you maybe provide a minimal example? I'm unable to reproduce the issue currently.

**Comment by grubersjoe** [comment]
Lack of feedback, closing.
