### ISSUE TITLE
Package size 

### ISSUE THREAD

**Issue by xanderim** [grubersjoe/react-activity-calendar#34]
Hey @grubersjoe, thank you for the great package!

Do you have any plans to reduce the package size? According to [Bundlephobia](https://bundlephobia.com/package/react-activity-calendar@2.0.2), the size is over 40 KB. Chroma-js alone takes up 14.5 KB, which is quite a lot. Once again, thank you for your work! Cheers!

**Comment by grubersjoe** [comment]
Hey @xanderim. Thanks for the hint, improving the bundle size is definitely something I'd also like to do. I'll look into it when I find time.

**Comment by grubersjoe** [comment]
Little update: I'm currently working on extracting the chroma.js parts. Very little of it is actually needed, but chroma.js is not tree shakable unfortunately.

**Comment by grubersjoe** [comment]
I've found a much better solution: don't use JavaScript at all to calculate the color scales but use a fancy new CSS feature: color-mix.

This way `chroma.js` could be removed completely which saves around 16 kB (gzipped) which is a reduction by around 43% :)
https://bundlephobia.com/package/react-activity-calendar@2.6.0
