### ISSUE TITLE
Allow arbitrary number of levels

### ISSUE THREAD

**Issue by eschreiner** [grubersjoe/react-activity-calendar#37]
Hi there,

first of all, thank you for sharing this component.

I would like to use more than the 5 levels. Is that possible at all? The internal rendering of the blocks seems to account only for 5 different fills...

Thank you!

**Comment by grubersjoe** [comment]
Hey. Good idea, like it :). There is no good reason that only five levels are supported and it should be easy to implement any amount. The number originates from earlier when this component was part of `react-github-calendar` that uses five levels like GitHub.

I've started a branch to work on it.

**Comment by grubersjoe** [comment]
Released in `react-activity-calendar@2.2.0`. Check out the [demo](https://grubersjoe.github.io/react-activity-calendar/?path=/story/react-activity-calendar--activity-levels).

**Comment by eschreiner** [comment]
Hi Jonathan,

upgraded to 2.2.0 - works like a charm!

![grafik](https://github.com/grubersjoe/react-activity-calendar/assets/184471/02e8add8-5725-4959-82ac-fbf29323b3b9)

Thank you so much for the timely response.

**Comment by grubersjoe** [comment]
Nice screenshot :). Glad that it works well for your use case!
