### ISSUE TITLE
SyntaxError: Unexpected token 'export', when using in Next.js

### ISSUE THREAD

**Issue by wansaleh** [grubersjoe/react-activity-calendar#4]
Hi. Thanks for the awesome component.

However I was unable to make this component work with my app, as soon as I imported the package, Next.js throws `SyntaxError: Unexpected token 'export'` error.

I see your package imports date functions from `date-fns/esm` instead of `date-fns`. All this time I cannot make `date-fns/esm` packages to work with Next.js, so I think that's the issue. How do I resolve this?

Thanks in advance.

**Comment by grubersjoe** [comment]
Hey, thanks for pointing this out. Yeah, I suppose sticking to ESM is a bit too early. I changed the imports to use the different `date-fns` submodules. Should work now in v1.2.1!
