### ISSUE TITLE
Add date fields to ActivityCalendar Component

### ISSUE THREAD

**Issue by codefromrvk** [grubersjoe/react-activity-calendar#45]
This is a request PR to have `startDate` and `endDate` as prop to the ActivityCalendar. This is needed because when the data is not sorted, the component takes the first value of array as `startDate`.

Eg:
```js
  <ActivityCalendar
      startDate="2023-01-01"
      colorScheme="light"
      data={[
        {
          date: "2023-06-22",
          count: 16,
          level: 4,
        },
        {
          date: "2023-01-01",
          count: 16,
          level: 3,
        }]}
    />
```
Instead of providing the dates as prop, if the component can itself can detect the smallest and largest date , that would be great!

**Comment by codefromrvk** [comment]
What if you need the empty boxes but there is no data for it? @grubersjoe

**Comment by grubersjoe** [comment]
Add one more empty entry at the beginning of the data array with the desired date. The calendar will take this date as start and fill holes with empty blocks.

**Comment by codefromrvk** [comment]
Yup that is what I am currently doing.
