### ISSUE TITLE
Displaying incorrect dates when timezone is Argentina. GMT-2.

### ISSUE THREAD

**Issue by JaitenThomas** [grubersjoe/react-activity-calendar#51]
To replicate: Set your system settings to Argentina (GMT-2) timeZone.

When I have my <ActivityCalender /> data property set to
```typescript
activities: [
      {
        count: 0,
        level: 0,
        date: '2024-01-05'
      },
      {
        count: 0,
        level: 0,
        date: '2024-01-19'
      }
    ]
``` 
The starting date on the UI for the activity calendar is incorrect (in the screenshot below I'm hovering over the first square, which displays as the 4th but the first activity date as seen in above code is '2024-01-05')
![Todochallenge-Turn-your-challenges-into-habit (2)](https://github.com/grubersjoe/react-activity-calendar/assets/46008388/f50cc2e5-0b2d-4245-8ee5-bc7df7c8aca1).

**Comment by JaitenThomas** [comment]
Closed as the issue that isn't related to this package. It was related to my code base.

Just a note for anyone else experiencing this: when you use activity.date and you want to display it you need to first parse it when format using date-fns:

```typescript
format(
    parse(activity.date, 'yyyy-MM-dd', new Date()),
    'EEEE d MMMM yyyy',
  )
```  
Here is a chatGPT explanation:
When working with date and time values in JavaScript, the Date object is sensitive to time zones, and its behavior can be influenced by the local time zone of the system. In scenarios where you're dealing with date strings and want consistent results, providing a reference date, as done with new Date() in date-fns when parsing, helps establish a context for the time zone offset. This is particularly useful when parsing date strings without explicit time-related information and ensures consistent interpretation, especially in cases like Argentina Standard Time (ART) where there might be a specific time zone offset.

**Comment by grubersjoe** [comment]
Out of interest: how exactly did you use the component? I assume you formatted date inside tooltip somehow? Out of the box if you just pass the data it should show the correct day independent of the time zone I think

**Comment by JaitenThomas** [comment]
It saved the date gotten from activity.date in redux state,

and to use it I had to do it like this:

`formatISO(parseISO(item), {
            representation: 'date',
          })`

(parseISO, is better way of doing)

`parse(activity.date, 'yyyy-MM-dd', new Date())`

both formatISO and parseISO come from date-fns.

So the fix would be wrapping the activity.date with parseISO, which you could add directly into the library when you use formatISO.

**Comment by grubersjoe** [comment]
Thanks for the explanation. I checked, there's only one place in the library where `formatISO()` is called and it uses `parseISO()` before so that should be fine.

**Comment by JaitenThomas** [comment]
That is good!

In summary, when passing the activity.date into a date-fns format() method in your own codebase you have to re-parse it.

```typescript
format(
    parseISO(activity.date),
    'EEEE d MMMM yyyy',
  )
```
