### ISSUE TITLE
How to add click event?

### ISSUE THREAD

**Issue by zpaimon** [grubersjoe/react-activity-calendar#7]
hi
 I want to add click event at rect ,but I don't know how to do ?
thanks.

**Comment by grubersjoe** [comment]
Hey. I've added a property that allows to register event handlers. Simply update to v1.4.0 and check out docs here:
https://grubersjoe.github.io/react-activity-calendar/?path=/story/activity-calendar--event-handlers

**Comment by karljinang** [comment]
<ActivityCalendar 
  data={data}  
  eventHandlers: {
    onClick: event => activity => {
      console.log({ event, activity });
      alert(JSON.stringify(activity, null, 4));
    },
    onMouseEnter: event => activity => console.log('mouseEnter'),
  }
/>
