### ISSUE TITLE
Responsive width for mobile viewport

### ISSUE THREAD

**Issue by mattwelter** [grubersjoe/react-activity-calendar#98]
I love the component! Works really well

I'm trying to make the activity calendar width responsive to the parent div.

I see that there is a "narrow screen" example in the docs, but it doesn't show how to set that up.

The only way to do that right now is by reading the parent div width and slicing the data at the perfect length in order to make the activity calendar responsive to the mobile viewport.

Is there a way right now to do that? Is it possible to add a prop "width": 100% or "width": 375px?

Thanks!

**Comment by grubersjoe** [comment]
Hey. Does the "narrow screen" example behave like you want it to? Or do want to work around horizontal scrolling? If the parent container is not wide enough for the component, horizontal scrolling should "just work". In the story the parent div simply has a fixed width of 480px:

<img width="1415" alt="image" src="https://github.com/grubersjoe/react-activity-calendar/assets/3109364/dea9b6fb-df3e-4eca-968e-8d4709d0af61">

Can you provide some example code to illustrate the issue better?
https://codesandbox.io/s/react-new

**Comment by mattwelter** [comment]
The activity calendar overflows outside of the parent div, but I fixed it by adding overflow-y: scroll; to the parent div. Good now!
